package service

import (
	"edu/model"
	"edu/repository"
	stdErrors "errors"

	"github.com/pkg/errors"
)

/*
// const (
// 	SUPERUSER_NAME     = "admin"
// 	SUPERUSER_PASSWORD = "123456"
// )

// func init() {
// 	// This init logic is problematic after Admin model refactor.
// 	// Superuser creation should be handled by the InitSuperUser endpoint or a dedicated setup script.
// 	// It would require creating a User first, then an Admin.
// 	// Commenting out for now.

// 	// _, err := AdminSvr.SelectAdminByUsername(SUPERUSER_NAME) // This method itself needs refactor
// 	// if err == gorm.ErrRecordNotFound {
// 	// 	// Create User first
// 	// 	// user := model.User{Username: SUPERUSER_NAME, Password: SUPERUSER_PASSWORD, ...}
// 	// 	// createdUser, _ := UserSvr.CreateUser(user)

// 	// 	// admin := model.Admin{
// 	// 	// 	UserID: createdUser.ID,
// 	// 	// 	Status:   model.ADMIN_STATUS_OK,
// 	// 	// }
// 	// 	// AdminSvr.CreateAdmin(admin)
// 	// }
// }
*/

var AdminSvr *AdminService = &AdminService{
	baseService: newBaseService(),
}

type AdminService struct {
	baseService
}

// CreateAdminRole creates a new admin role.
func (svr *AdminService) CreateAdminRole(role model.AdminRole) (*model.AdminRole, error) {
	// Ensure role.ID is 0 for creation.
	role.ID = 0
	// Check if role with the same slug already exists
	existingRole, err := repository.AdminRoleRepo.FindBySlug(role.Slug)
	if err != nil {
		return nil, errors.Wrap(err, "failed to check for existing admin role by slug")
	}
	if existingRole != nil {
		return nil, stdErrors.New("admin role with this slug already exists")
	}

	err = repository.AdminRoleRepo.Create(&role)
	if err != nil {
		return nil, errors.Wrap(err, "failed to create admin role")
	}
	return &role, nil
}

// SelectAdminRoleById retrieves an admin role by its ID.
func (svr *AdminService) SelectAdminRoleById(id uint) (*model.AdminRole, error) {
	if id == 0 {
		return nil, stdErrors.New("invalid admin role ID")
	}
	role, err := repository.AdminRoleRepo.FindByID(id)
	if err != nil || role == nil {
		return nil, stdErrors.New("admin role not found")
	}
	return role, nil
}

// SelectAdminRoleBySlug retrieves an admin role by its slug.
func (svr *AdminService) SelectAdminRoleBySlug(slug string) (*model.AdminRole, error) {
	if slug == "" {
		return nil, stdErrors.New("slug cannot be empty")
	}
	role, err := repository.AdminRoleRepo.FindBySlug(slug)
	if err != nil || role == nil {
		return nil, stdErrors.New("admin role not found with this slug")
	}
	return role, nil
}

// GetAdminRolePermissions retrieves all permissions associated with a given AdminRoleID.
// This assumes a many-to-many relationship table: AdminRolePermissionRelation (role_id, permission_id)
// Or direct permission slugs stored in AdminRole. For now, let's assume a join table.
// If AdminRolePermissionRelation is not generated by DAO, this needs adjustment.
// For simplicity, if no explicit relation table, this might return permissions based on role slug patterns.
// Placeholder: Actual implementation depends on how permissions are linked to roles.
func (svr *AdminService) GetAdminRolePermissions(roleID uint) ([]*model.AdminPermission, error) {
	// Example: if AdminRolePermissionRelation table exists and is managed by DAO
	// relations, err := repository..Where(repository..RoleId.Eq(roleID)).Find()
	// if err != nil {
	// 	return nil, errors.Wrap(err, "failed to get role-permission relations")
	// }
	// var permIDs []uint
	// for _, rel := range relations {
	// 	permIDs = append(permIDs, rel.PermissionId)
	// }
	// if len(permIDs) == 0 {
	// 	return []*model.AdminPermission{}, nil
	// }
	// return repository..Where(repository..ID.In(permIDs...)).Find()

	// Simplified: If permissions are determined by role slug or other logic not involving a direct join table query here.
	// This part needs to be implemented based on the actual permission model.
	// For now, returning an empty list.
	// A common pattern is to have a table AdminRolePermission with RoleID and PermissionID.
	// If such a table (e.g., model.AdminRolePermission) and its DAO (repository.) exist:
	/*
		var rolePerms []*model.AdminRolePermission
		err := repository..Where(repository..RoleID.Eq(roleID)).Find(&rolePerms)
		if err != nil {
			return nil, errors.Wrap(err, "failed to fetch role permissions")
		}
		if len(rolePerms) == 0 {
			return []*model.AdminPermission{}, nil
		}
		permissionIDs := make([]uint, len(rolePerms))
		for i, rp := range rolePerms {
			permissionIDs[i] = rp.PermissionID
		}
		return repository..Where(repository..ID.In(permissionIDs...)).Find()
	*/
	// If permissions are directly on AdminRole as a list of slugs, logic would be different.
	// For now, let's assume a join table `admin_role_permissions` (RoleID, PermissionID)
	// and a corresponding DAO `repository.`.
	// If this DAO doesn't exist, this will fail.
	// This is a placeholder and needs to be adapted to the actual schema for role-permission linkage.
	// Let's assume for now that permissions are not directly queryable this way via AdminService
	// and might be handled by checking permission slugs against a role's defined permission set.
	// Or, if AdminRole has a direct field like PermissionSlugs []string.
	// For the purpose of this refactor, we'll return an empty slice.
	// The actual permission checking logic will be crucial.
	// A more robust way: AdminRole has many AdminPermissions through a join table.
	// GORM can handle this with Preload if models are set up correctly.
	// e.g. repository..Preload(repository..Permissions).Where(repository..ID.Eq(roleID)).First()
	// This requires AdminRole model to have a `Permissions []*AdminPermission `gorm:"many2many:admin_role_permissions;"` field.

	// TODO: 实现角色权限关联查询
	// 当前返回空列表
	return []*model.AdminPermission{}, nil
}

// GetUserPermissions retrieves all permissions for a given userID.
func (svr *AdminService) GetUserPermissions(userID uint) ([]*model.AdminPermission, error) {
	user, err := UserSvr.SelectUserById(userID) // Assuming UserSvr.SelectUserById preloads AdminRole if needed, or we do it here.
	if err != nil {
		return nil, errors.Wrap(err, "failed to get user for permissions check")
	}
	if user == nil {
		return nil, stdErrors.New("user not found for permissions check")
	}

	if !user.IsAdmin {
		return []*model.AdminPermission{}, nil // Not an admin, no admin permissions
	}

	// Superuser (e.g., username "admin") gets all permissions
	// TODO: Use a constant for superuser username
	if user.Username == "admin" {
		permissions, err := repository.AdminPermRepo.FindAll()
		if err != nil {
			return nil, errors.Wrap(err, "failed to get all permissions for superuser")
		}
		return permissions, nil
	}

	if user.AdminRoleID == nil || *user.AdminRoleID == 0 {
		return []*model.AdminPermission{}, nil // Admin but no role assigned
	}

	return svr.GetAdminRolePermissions(*user.AdminRoleID)
}

func (svr *AdminService) AdminMenu() []model.Menu {
	return model.AdminMenu
}

func (svr *AdminService) AdminPermission() []string {
	return []string{"sys:user:add", "sys:user:edit", "sys:user:delete", "sys:user:import", "sys:user:export"}
}
